### ISSUE TITLE
Different font face setting for the minibuffer?

### ISSUE THREAD

**Issue by akartha** [protesilaos/fontaine#9]
Hi Prot

Is it feasible to have the main buffer and the mini-buffer font faces set separately?

I use fontaine to set a generously large font size whenever I am doing long form reading - but I do not want size 220 font height in my mini buffer when trying to run a command on the text or switch buffers.

Appreciate your work Prot!

**Comment by protesilaos** [comment]
> From: akartha ***@***.***>
> Date: Fri, 11 Oct 2024 16:55:14 -0700
>
> Hi Prot

Hello there!

> Is it feasible to have the main buffer and the mini-buffer font faces
> set separately?

I principle, yes, though I don't think we can do this in a clean way via
'fontaine'. The reason is that the minibuffer does not use a separate
face for its contents: it is just the 'default', which is what applies
everywhere.

To get the minibuffer to a smaller height we need to use the "remap"
functionality to change the meaning of the 'default' face in the
minibuffer only. This should work, but it is not part of the 'fontaine'
infrastructure. If you are interested, I am happy to prepare the code
for you.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by akartha** [comment]
Thank you Prot

It's a nice to have. I'd appreciate it if you do get a chance to look at it, but no urgency.

Arun

**Comment by protesilaos** [comment]
> From: akartha ***@***.***>
> Date: Wed, 16 Oct 2024 18:41:17 -0700
>
> Thank you Prot

You are welcome!

> It's a nice to have. I'd appreciate it if you do get a chance to look
> at it, but no urgency.

Here is the code:

    (defvar-local my-minibuffer-font-remap-cookie nil
      "The current face remap of `my-minibuffer-set-font'.")

    (defface my-minibuffer-default
      '((t :height 0.8))
      "Face for the minibuffer.")

    (defun my-minibuffer-set-font ()
      (setq-local my-minibuffer-font-remap-cookie
                  (face-remap-add-relative 'default 'my-minibuffer-default)))

    (add-hook 'minibuffer-mode-hook #'my-minibuffer-set-font)

Notice that I have made it 0.8 times the default font height. Tweak that
as you see fit.

-- 
Protesilaos Stavrou
https://protesilaos.com
